ROSETTA_STONE = {
    ('E', 1):  "UConn         ",
    ('E', 2):  "Iowa State    ",
    ('E', 3):  "Illinois      ",
    ('E', 4):  "Auburn        ",
    ('E', 5):  "San Diego St. ",
    ('E', 6):  "BYU           ",
    ('E', 7):  "Washington St.",
    ('E', 8):  "FAU           ",
    ('E', 9):  "Northwestern  ",
    ('E', 10): "Drake         ",
    ('E', 11): "Duquesne      ",
    ('E', 12): "UAB           ",
    ('E', 13): "Yale          ",
    ('E', 14): "Morehead St.  ",
    ('E', 15): "S Dakota St.  ",
    ('E', 16): "Stetson       ",
    ('W', 1):  "UNC           ",
    ('W', 2):  "Arizona       ",
    ('W', 3):  "Baylor        ",
    ('W', 4):  "Alabama       ",
    ('W', 5):  "Saint Mary's  ",
    ('W', 6):  "Clemson       ",
    ('W', 7):  "Dayton        ",
    ('W', 8):  "Miss-ippi St. ",
    ('W', 9):  "Michigan St.  ",
    ('W', 10): "Nevada        ",
    ('W', 11): "New Mexico    ",
    ('W', 12): "Grand Canyon  ",
    ('W', 13): "Charleston    ",
    ('W', 14): "Colgate       ",
    ('W', 15): "Long Beach St.",
    ('W', 16): "Wagner        ",
    ('S', 1):  "Houston       ",
    ('S', 2):  "Marquette     ",
    ('S', 3):  "Kentucky      ",
    ('S', 4):  "Duke          ",
    ('S', 5):  "Wisconsin     ",
    ('S', 6):  "Texas Tech    ",
    ('S', 7):  "Florida       ",
    ('S', 8):  "Nebraska      ",
    ('S', 9):  "Texas A&M     ",
    ('S', 10): "BOIS/COL      ",
    ('S', 11): "NC State      ",
    ('S', 12): "James Madison ",
    ('S', 13): "Vermont       ",
    ('S', 14): "Oakland       ",
    ('S', 15): "Western KY    ",
    ('S', 16): "Longwood      ",
    ('M', 1):  "Purdue        ",
    ('M', 2):  "Tennessee     ",
    ('M', 3):  "Creighton     ",
    ('M', 4):  "Kansas        ",
    ('M', 5):  "Gonzaga       ",
    ('M', 6):  "South Carolina",
    ('M', 7):  "Texas         ",
    ('M', 8):  "Utah State    ",
    ('M', 9):  "TCU           ",
    ('M', 10): "Colorado State",
    ('M', 11): "Oregon        ",
    ('M', 12): "McNeese       ",
    ('M', 13): "Samford       ",
    ('M', 14): "Akron         ",
    ('M', 15): "Saint Peter's ",
    ('M', 16): "MTST/Grambling"
}